// src/vue/pages/Displays/Status/InOut.vue
<template>
  <div class="col-12 q-pa-sm">
    <q-card class="full-width">
      <q-card-section>
        <div class="text-subtitle">
          {{ $tt("display", "title", status_in.status) }}
        </div>
      </q-card-section>
      <q-separator />
      <q-list class="row">
        <q-item
          v-for="(order, index) in orders"
          :key="index"
          class="col-12 col-sm-4 col-md-3 col-lg-2 q-pa-sm"
        >
          <q-card class="q-mb-md full-width">
            <q-card-section>
              <q-item-label>
                {{ $tt("display", "label", "Order") }} #{{
                  order.order_product.order.id
                }}
              </q-item-label>
              <q-item-label>
                {{ order.order_product.order.client?.name }}
              </q-item-label>
              <q-item-label caption>
                <q-icon
                  v-if="order.status?.icon"
                  :color="order.status?.color"
                  :name="order.status?.icon"
                  class="q-mr-sm"
                />
                <q-item-label caption>
                  Horário do pedido:
                  {{
                    new Date(order.registerTime).toLocaleTimeString("pt-br", {
                      hour: "2-digit",
                      minute: "2-digit",
                    })
                  }}
                </q-item-label>
                <q-item-label caption v-if="order.registerTime != order.updateTime">
                  Iniciou nesse status:
                  {{
                    new Date(order.updateTime).toLocaleTimeString("pt-br", {
                      hour: "2-digit",
                      minute: "2-digit",
                    })
                  }}
                </q-item-label>
              </q-item-label>
            </q-card-section>
            <q-card-section>
              <q-item-label caption>
                {{ order.order_product.quantity }}
                {{ order.order_product.product.product }}(s)
              </q-item-label>
            </q-card-section>
            <q-card-actions v-if="status_working">
              <q-btn
                class="full-width"
                color="primary"
                :label="$tt('display', 'btn', 'start')"
                @click="start(order)"
              />
            </q-card-actions>
          </q-card>
        </q-item>
      </q-list>
    </q-card>
  </div>
</template>
<script>
import { mapActions, mapGetters } from "vuex";

export default {
  props: {
    status_in: {
      requered: true,
    },
    status_working: {
      default: null,
    },
    status_out: {
      default: null,
    },
    orders: {
      requered: true,
    },
  },
  methods: {
    ...mapActions({
      setOrderProductQueues: "order_products_queue/save",
    }),
    start(order) {
      this.setOrderProductQueues({
        id: order.id,
        status: this.status_working["@id"],
      }).finally(() => {
        this.$emit("reload");
      });
    },
  },
};
</script>

// src/react/pages/displays/Status/InOut.js
import React from 'react';
import { View } from 'react-native';
import { Card, Text, Button } from 'react-native-paper';
import { useStore } from '@store';

const InOut = ({ orders, status_in, status_working, onReload }) => {
    const store = useStore('order_products_queue');
    const { actions } = store;

    const start = async order => {
        await actions.save({
            id: order.id,
            status: status_working['@id'],
        });
        onReload();
    };

    return (
        <View style={{ width: '100%', padding: 8 }}>
            <Card>
                <Card.Title title={status_in?.status} />
                <Card.Content style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
                    {orders.map(order => (
                        <Card key={order.id} style={{ width: '100%', marginBottom: 8 }}>
                            <Card.Content>
                                <Text>Pedido #{order.order_product.order.id}</Text>
                                <Text>{order.order_product.order.client?.name}</Text>
                                <Text>
                                    Horário do pedido:{' '}
                                    {new Date(order.registerTime).toLocaleTimeString('pt-BR', {
                                        hour: '2-digit',
                                        minute: '2-digit',
                                    })}
                                </Text>
                                {order.registerTime !== order.updateTime && (
                                    <Text>
                                        Iniciou nesse status:{' '}
                                        {new Date(order.updateTime).toLocaleTimeString('pt-BR', {
                                            hour: '2-digit',
                                            minute: '2-digit',
                                        })}
                                    </Text>
                                )}
                                <Text>
                                    {order.order_product.quantity}{' '}
                                    {order.order_product.product.product}(s)
                                </Text>
                            </Card.Content>

                            {status_working && (
                                <Card.Actions>
                                    <Button mode="contained" onPress={() => start(order)}>
                                        Iniciar
                                    </Button>
                                </Card.Actions>
                            )}
                        </Card>
                    ))}
                </Card.Content>
            </Card>
        </View>
    );
};

export default InOut;
